from typing import Protocol
from uuid import UUID

from app.domain.entities.pluggy_item import PluggyItem


class PluggyItemRepository(Protocol):
    async def get_by_id(self, item_id: UUID) -> PluggyItem | None: ...

    async def get_by_pluggy_item_id(self, pluggy_item_id: str) -> PluggyItem | None: ...

    async def list_by_user_id(self, user_id: UUID) -> list[PluggyItem]: ...

    async def create(self, item: PluggyItem) -> PluggyItem: ...

    async def update(self, item: PluggyItem) -> PluggyItem: ...

    async def delete(self, item_id: UUID) -> bool: ...
