"""create_pluggy_items_and_sync_logs

Revision ID: 34516556ab7c
Revises: dab3766f1965
Create Date: 2026-09-05 20:13:23.371163

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34516556ab7c"
down_revision: str | Sequence[str] | None = "dab3766f1965"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pluggy_items",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("pluggy_item_id", sa.String(length=64), nullable=False),
        sa.Column("connector_id", sa.Integer(), nullable=True),
        sa.Column("connector_name", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pluggy_items_pluggy_item_id"),
        "pluggy_items",
        ["pluggy_item_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_pluggy_items_status"), "pluggy_items", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_pluggy_items_user_id"), "pluggy_items", ["user_id"], unique=False
    )
    op.create_table(
        "sync_logs",
        sa.Column("pluggy_item_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pluggy_item_id"], ["pluggy_items.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sync_logs_created_at"), "sync_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_sync_logs_event_type"), "sync_logs", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_sync_logs_pluggy_item_id"),
        "sync_logs",
        ["pluggy_item_id"],
        unique=False,
    )
    op.create_index(op.f("ix_sync_logs_status"), "sync_logs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sync_logs_status"), table_name="sync_logs")
    op.drop_index(op.f("ix_sync_logs_pluggy_item_id"), table_name="sync_logs")
    op.drop_index(op.f("ix_sync_logs_event_type"), table_name="sync_logs")
    op.drop_index(op.f("ix_sync_logs_created_at"), table_name="sync_logs")
    op.drop_table("sync_logs")
    op.drop_index(op.f("ix_pluggy_items_user_id"), table_name="pluggy_items")
    op.drop_index(op.f("ix_pluggy_items_status"), table_name="pluggy_items")
    op.drop_index(op.f("ix_pluggy_items_pluggy_item_id"), table_name="pluggy_items")
    op.drop_table("pluggy_items")
    # ### end Alembic commands ###
